### ISSUE TITLE
Edit in iD or Potlatch

### ISSUE THREAD

**Issue by 1ec5** [osmlab/fixing-polygons-in-osm#10]
It’d be nice to have an easy way to open the problematic features in my default osm.org editor, whether it’s iD or Potlatch. It looks like the osm.org URL scheme only supports specifying one way or node to select at a time, but even that would be enough for me to spot the error in most cases.

**Comment by joto** [comment]
@1ec5 Not sure what you mean here. Do you want this on the comparison map at http://area.jochentopf.com/map/index.html or where? Currently the best way of finding and fixing problems is on the OSM Inspector (http://tools.geofabrik.de/osmi/?view=areas) which can open your favourite editor.

**Comment by 1ec5** [comment]
Hm, I honestly don’t remember if I was looking at the comparison map or not. 😄 All I remember is that the tool had only a JOSM button. It isn’t a big deal in any case.
