### ISSUE TITLE
Richier stats about MP would help

### ISSUE THREAD

**Issue by d1g** [osmlab/fixing-polygons-in-osm#12]
More light on this topic will help mappers and data consumers to write custom software/complex custom queries.
- How many valid MP consist only of `outer rings`, without any `inner` rings?
  - additionally, how many of them have touching/glued (at least one) ring(s)?
- How many valid MP consist of single `outer` ring?
- <s>How many valid MP `inner rings` are used in (other MP) as `outer rings` (inner-outer-inner implemented using multiple MP); according to [our current page](http://wiki.openstreetmap.org/wiki/Relation:multipolygon#Valid_Multipolygon_conditions) this is still valid (probably problematic for some data consumers)</s>
- How many valid MP have [touching `inner rings`](http://wiki.openstreetmap.org/wiki/Relation:multipolygon#Touching_inner_rings) (clearly problematic for some data consumers)

We have taginfo to inspect primitive stats about tags, but we don't have stats or even yearly public reports about what do we have in "relations".

**Comment by mboeringa** [comment]
> How many valid MP inner rings are used in (other MP) as outer rings (inner-outer-inner implemented using multiple MP); according to our current page this is still valid (clearly problematic for some data consumers)

While maybe an interesting statistic, I think this particular condition is not an issue, and certainly doesn't require "fixing" of the multipolygons by duplicating data and ways. That would be even counter productive.

Ways are ways, they should be treated irrespective of to how many relations they are assigned, and in what role.

E.g. we also wouldn't want routes to duplicate ways if the route follows a way that is already used for another route? That would quickly lead to a completely unmanageable edit situation, with potentially dozens of independent ways stacked on top of each other.

If a data consumer application can't handle this, then the application needs fixing, not the OSM data.

**Comment by joto** [comment]
A lot of statistics are available on the http://area.jochentopf.com site. More are created or can be created based on the tools at https://github.com/osmcode/osm-area-tools .

Regarding the touching inner rings: This is allowed in OSM and there is really no problem to correctly identify those cases and create proper multipolgons from them data all data consumers can use.

**Comment by joto** [comment]
I agree that we do want more stats, but the area.jochentopf.com site is only a temporary site and I am not planning to add more. I have been working on [these tools](https://github.com/osmcode/osm-data-anomaly-detection) which can create some more detailed stats. Not sure yet how and where I'll show the stats generated from these programs, but I'll want to get them somewhere. Closing here.
