### ISSUE TITLE
Disk space

### ISSUE THREAD

**Issue by pnorman** [osmlab/fixing-polygons-in-osm#14]
![image](https://cloud.githubusercontent.com/assets/1190866/17791300/5266e97a-654f-11e6-82b6-e158f0f52182.png)

1% is about 10GB for /. Something seems to have consumed a bunch of disk space in the last two weeks. It's not the DB, that only went up <10GB in that timeframe, and the tile store seems to be about the same. It's current usage is okay but I'm worried because I have no idea what it is. Could it be a runaway logfile?

**Comment by joto** [comment]
@pnorman not the right place to discuss this. This has nothing to do with fixing polygons. I am just using the machine for some other, unrelated experiments.
