### ISSUE TITLE
"uninteresting"/"unimportant" tag list for detecting old-style polygons

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/fixing-polygons-in-osm#18]
I didn't find any information, so maybe somebody can help me.

What is the full  "uninteresting"/"unimportant" tag list for detecting Old-style polygons ?
 
My first guess :  the keys from [osm2pgsql default syle](https://github.com/openstreetmap/osm2pgsql/blob/master/default.style) , marked with 'delete'  
```
note
note:*
source
source_ref
source:*
attribution
comment
fixme
created_by
odbl
odbl:note
SK53_bulk:load
tiger:*
NHD:*
nhd:*
gnis:*
geobase:*
accuracy:meters
sub_sea:type
waterway:type
KSJ2:*
yh:*
osak:*
kms:*
ngbe:*
naptan:*
CLC:*
3dshapes:ggmodelk
AND_nosr_r
import
it:fvg:*
```

We have a better definitions ?

**Comment by grischard** [comment]
JOSM also has `converted_by` and `import` in the keys it considers discardable.

I'd add `history` and `FIXME`.

**Comment by tyrasd** [comment]
Maybe also add `name` and `name:*` (and similar tags like `ref`, etc.)?

A completely different approach would be to flag every multipolygon that has no *area tag* set. One could use an inverse version of [osm-polygon-features](https://github.com/tyrasd/osm-polygon-features/blob/master/polygon-features.json) or [id-area-keys](https://github.com/osmlab/id-area-keys) for that (maybe with added variants of the respective tags, e.g. `disused:<area-key>`, `abandoned:<area-key>`, etc.). This approach could maybe result in a few false-positives, but wouldn't overlook any otherwise possibly false negatives.

**Comment by grischard** [comment]
@tyrasd it would be very interesting to compare the two. The relevant and slightly complex piece of code, in JOSM, is [hasAreaTags](https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/data/osm/OsmPrimitive.java#L1354).

It's interesting how these three sources have slightly different ideas of what's an area and what isn't.

**Comment by ImreSamu** [comment]
@tyrasd 

>Maybe also add name and name:* (and similar tags like ref, etc.)?

In my mind we have a 4 category of osm keys
* Primary OSM keys  / name spaces 
   * `aeroway|amenity|attraction|barrier|boundary|building|craft|... `
   * `abandoned:|proposed:|planned:|removed:|razed:|disused:|demolished:|seamark:|was:` ....
* Secondary OSM keys (   without the primary OSM keys -  it is a probably a tagging problems ) 
   * `wheelchair|wikipedia|wikidata|layer|ref|url|phone|website|....`
   * `area`
   * `name` ; `name:*` ; `alt_name` ....
   * ....
*  "uninteresting"/"unimportant" OSM keys ( for  detecting Old-style polygons )
*   Other keys ( none of the above  )

I would like to separate the  tagging errors and  the old-style polygons.

So they are maybe a tagging problems ( no primary osm keys )
* `name=, type=multipolygon,`
* `area=, type=multipolygon,`
* `area=, type=multipolygon, smoking=, wheelchair=, description=,`
* `type=multipolygon, wheelchair=,`
* `type=multipolygon, wikipedia=,`

And they are  maybe an old-style multipolygons candidates ( only  "uninteresting"/"unimportant" OSM keys  )
* `note=, type=multipolygon,`
* `type=multipolygon, created_by=,`
* `type=multipolygon, fixme=,`

>A completely different approach would be to flag every multipolygon that has no area tag set.
>  One could use an inverse version of osm-polygon-features or id-area-keys  ...

my approach is similar ; 
*  find every relations/multipolygons (tag combinations) without a "Primary OSM keys" 
see: https://github.com/ImreSamu/osm_simple_relation_analyzer201703/blob/master/docs/germany-latest.osm.pbf_FREQ_RELATION_OUTER.md
And thank you for the links,  I will try to merge with my primary key list.

**Comment by joto** [comment]
I don't think we have to make it all so complicated. Just fixing everything that has no tag except `type=multipolygon` and we are a good way there. Ignoring `source` and `created_by` and we get almost 100%. After that we can look at other tags and the obvious place is osm2pgsql. Whatever osm2pgsql thinks is old-style will have to be dealt with eventually. If you start looking more closely into the tag combinations, you'll get to many things that aren't really about fixing old-style multipolygons but general "fixing of suspect" data, and that's not are focus here.

**Comment by ImreSamu** [comment]
side note:   As I see the [NEW Lua based openstreetmap-carto version](https://github.com/gravitystorm/openstreetmap-carto/tree/lua) will have more  "unwanted" keys,  than the current version.  See `delete_tags`, `delete_prefixes`  in [openstreetmap-carto.lua](https://github.com/gravitystorm/openstreetmap-carto/blob/lua/openstreetmap-carto.lua)
