### ISSUE TITLE
Old-style multipolygons from imports

### ISSUE THREAD

**Issue by joto** [osmlab/fixing-polygons-in-osm#3]
At least some of the old-style multipolygons are from imports. Lets identify those cases and discuss what the best way of handling them is together with the original importers (if we can find them) and the local communities affected.

Just from looking at the map of old-style multipolygons there are some hot-spots in Finland and the Southern US, among others. Lets start a list in this ticket and see what we know about these imports.

**Comment by sebastic** [comment]
All those old-style multipolygons have been fixed already. There is only the daily task of fixing the newly created old-style multipolygons left (almost exclusively created by iD users).
