### ISSUE TITLE
Include all old-style multipolygons in the old-style.osm.pbf file

### ISSUE THREAD

**Issue by sebastic** [osmlab/fixing-polygons-in-osm#32]
The updated [map](http://area.jochentopf.com/map/) shows old-style multipolygons which are not included in the [`old-style.osm.pbf`](http://area.jochentopf.com/download/old-style.osm.pbf).

Please include all the old-style multipolygons shown on the map in the `old-style.osm.pbf` file too.

I use that file as input for my fixing effort, iterating over its relations using the JOSM todo plugin.

**Comment by joto** [comment]
Sorry, I forgot to update the download area. This should now be in sync again.

**Comment by sebastic** [comment]
Thanks, I'm seeing a lot more relations in my sub-region extracts now.
