### ISSUE TITLE
Same tag on outer way as within relation

### ISSUE THREAD

**Issue by DaveF63** [osmlab/fixing-polygons-in-osm#38]
Hi
https://www.openstreetmap.org/way/191082117
Note the way contains the same tag as the relation
 
Is there a reason the above case wasn't included in the clean up?

**Comment by joto** [comment]
It might well be that this slipped through, figuring out why this was the case would be difficult and probably impossible. With such a huge effort it is likely that some things would fall through the cracks. Please fix it!

**Comment by DaveF63** [comment]
Hmm...  If you feel entitled to claim all old style MP relations have been removed, you should do it.
A tag which renders on the outer way is quite basic, a bit hard to miss.

**Comment by joto** [comment]
http://area.jochentopf.com/stats/#old_style_multipolygons looks pretty good. I can't run after each and every instance.

**Comment by DaveF63** [comment]
That table is for those without rendering tags in the relation. However, even with tags in the relations, if there are corresponding rendering tags on the way it's still an 'old style' relation. I think you should rescind your claim & relaunch, using valid validation software.
These are just a few incorrect 'natural=wood' MP relations around London: http://overpass-turbo.eu/s/AIz

**Comment by mboeringa** [comment]
> Hmm... If you feel entitled to claim all old style MP relations have been removed, you should do it.
> A tag which renders on the outer way is quite basic, a bit hard to miss.

@DaveF63 . None of the existing editor software actually physically prevents you from creating "new" "old-style" multipolygons. Thus I have no doubt many new ones will be created in the course of time. Unless all editor software is redesigned to prevent this error, cleaning up "old-style" MPs is a continuous maintenance effort.

Maybe @joto should re-launch the clean-up effort each half year or so, to keep the number of them to a bare minimum, and we can all join in to help fix them.

Expecting @joto to clean up the mess himself, is not realistic considering the size of the potential problem... this is a community project after all!

**Comment by HolgerJeromin** [comment]
@mboeringa 
This is no discussion about house keeping for new stuff.

The linked way+relation is 4 years old! So the question is:
How many other ways were missed, too?

[jotos blog post](https://blog.jochentopf.com/2017-08-28-polygon-fixing-effort-concluded.html) said:

> No old-style multipolygons are now left (except a few that are created anew here and there, most likely by mappers who don’t know yet that the rules changed.)

And Dave proves this was wrong.

**Comment by joto** [comment]
The multipolygon in question here isn't a clearcut old-style multipolygon, it is tagged wrong and always was, irrespective if we interpret it as old-style or new-style. There never was a clear definition of what happens if both the way and the relation are tagged like in this case, so this is simply bad tagging.

It is difficult for these kinds of things to decide what something is really supposed to be because there are conflicting tags here. What we should do is this: Find all overlapping areas that have likely conflicting tags (here `natural=wood` on one member way and `natural=water` on the other). So this is just part of a bigger problem that isn't related to the old-style vs. new-style change, it can simply happen if you have unrelated closed ways that overlap etc. Maybe somebody wants to tackle this...

**Comment by DaveF63** [comment]
Hi
@mboeringa
Re: `new.`
True, but irrelevant to my point.

Re: `'clean up the mess himself'`. Well, he told me to fix it, so I tell him to fix it. I also said he should relaunch the project which I believe was a` 'community' `one.

@joto

> The multipolygon in question here isn't a clearcut old-style multipolygon

~~I disagree:
"One particular sub-variant is that inner ways have the same tags as the outer ways. That is very deprecated and should be fixed."~~
https://wiki.openstreetmap.org/wiki/OSM_Inspector/Views/Areas#Inner_way_has_same_tags
Apologies I misread the above. But it is missing a comment about the duplication of tags on the outer. I think a note tag needs to be added to the way of the outer explaining it's an MP relation. Many contributors miss this thinking it's an untagged standard way.

Unsure of the relevance of `it is tagged wrong and always was`.
Unsure why you consider old style MPs as something different than `"simply bad tagging."`

> What we should do is this: Find all overlapping areas that have likely conflicting tags (here natural=wood on one member way and natural=water on the other).

No. What should be found are MPs with the same tag on the outer way that is on relation for that way. This is what my OP routine does.

The problem with declaring `"The old-style multipolygon relations are history!"` Is contributors see the MPs I highlighted, but think they're OK as they've been told they've all been updated.

As I said, I think the project needs to be rerun.
