### ISSUE TITLE
Tile server

### ISSUE THREAD

**Issue by joto** [osmlab/fixing-polygons-in-osm#4]
@pnorman I had to reboot the server and now the tile server is gone. Can you set it up so it runs properly on startup.

**Comment by pnorman** [comment]
restarted manually, still need to set up init.d

**Comment by pnorman** [comment]
Where should non-system init.d scripts go?

**Comment by joto** [comment]
@pnorman What's the state now. Do the minutely diffs work?

**Comment by pnorman** [comment]
I was having trouble with osmosis but haven't had a chance to reproduce outside of the replication script

**Comment by pnorman** [comment]
osmosis issues fixed, now catching up and i'll add the service script to run it in the background.

current lag is 7890m, should be caught up in a few hours. The catchup time / time processed is about 1-2 minutes per hour.

**Comment by pnorman** [comment]
caught up. remaining is
- [x] adding replicate as a service
- [ ] plugging in to expire tiles

**Comment by joto** [comment]
@pnorman Is the expire still open? Do we need to do something here?

**Comment by pnorman** [comment]
Still haven't done anything to make tiles expire. I also haven't checked in on the server to make sure that everything is running.

**Comment by joto** [comment]
Tile server has been disabled a while back. Closing.
