### ISSUE TITLE
Add "% of multipolygon that is broken" to http://area.jochentopf.com/stats/

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/fixing-polygons-in-osm#9]
Good overwiev, and for most purposes more important than raw number is what is the ratio of broken to correct multipolygons. Currently such grah is missing from http://area.jochentopf.com/stats/

**Comment by joto** [comment]
That number depends on what exactly is defined as broken. Also some areas might be broken in multiple ways, so we have to avoid counting them twice. The number is certainly much less that 1%.

**Comment by joto** [comment]
Never got around to this except the percentage of old-styles. As this project is slowly winding down, I don't think I'll add this any more.
